### ISSUE TITLE
0.0.6 does not copy dll files properly

### ISSUE THREAD

**Issue by Vortex2Oblivion** [SanicBTW/HxWebView#3]

**Comment by Vortex2Oblivion** [comment]
dll files do not get copied to export folder

**Comment by SanicBTW** [comment]
fuck

**Comment by Vortex2Oblivion** [comment]
also ive had reports of the dll files freaking out people's antivirus

**Comment by SanicBTW** [comment]
yeah its most likely to happen since its from an unknown site, but i can assure the dlls are from Microsoft themselves

**Comment by SanicBTW** [comment]
wait i just noticed i fucked up a dll import on assets

**Comment by SanicBTW** [comment]
![image](https://github.com/SanicBTW/HxWebView/assets/58010536/80c9d2c5-322f-42cb-86f8-b118af3eddb0)
aight pushing an update asap

**Comment by SanicBTW** [comment]
Fixed on https://github.com/SanicBTW/HxWebView/commit/8c9cf59b8cca6b2d44c30a04abab9f87e87e560d I will push a commit to update DLLs
